/* Copyright (c) 2026 Skyward Experimental Rocketry
 * Authors: Pietro Bortolus
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#pragma once

#include <utils/DependencyManager/DependencyManager.h>
#include <utils/Registry/RegistryFrontend.h>

namespace RIGv3
{

enum ConfigurationKeys
{
    // Ereg parameters
    CONFIG_ID_EREG_OX_FIRST_PRESSURIZATION_KP,
    CONFIG_ID_EREG_OX_FIRST_PRESSURIZATION_KI,
    CONFIG_ID_EREG_OX_FIRST_PRESSURIZATION_KD,
    CONFIG_ID_EREG_OX_RAMPUP_KP,
    CONFIG_ID_EREG_OX_RAMPUP_KI,
    CONFIG_ID_EREG_OX_RAMPUP_KD,
    CONFIG_ID_EREG_OX_PILOT_PRECHARGE,
    CONFIG_ID_EREG_OX_RAMPUP_PRECHARGE,
    CONFIG_ID_EREG_OX_FIRST_PRESSURIZATION_TARGET,
    CONFIG_ID_EREG_OX_RAMPUP_TARGET,

    CONFIG_ID_EREG_FUEL_FIRST_PRESSURIZATION_KP,
    CONFIG_ID_EREG_FUEL_FIRST_PRESSURIZATION_KI,
    CONFIG_ID_EREG_FUEL_FIRST_PRESSURIZATION_KD,
    CONFIG_ID_EREG_FUEL_RAMPUP_KP,
    CONFIG_ID_EREG_FUEL_RAMPUP_KI,
    CONFIG_ID_EREG_FUEL_RAMPUP_KD,
    CONFIG_ID_EREG_FUEL_PILOT_PRECHARGE,
    CONFIG_ID_EREG_FUEL_RAMPUP_PRECHARGE,
    CONFIG_ID_EREG_FUEL_FIRST_PRESSURIZATION_TARGET,
    CONFIG_ID_EREG_FUEL_RAMPUP_TARGET,

    // Firing sequence parameters
    CONFIG_ID_PILOT_FUEL_LEAD_TIME,
    CONFIG_ID_FULL_THROTTLE_TIME,
    CONFIG_ID_LOW_THROTTLE_TIME,
    CONFIG_ID_PILOT_FLAME_OX_POSITION,
    CONFIG_ID_PILOT_FLAME_FUEL_POSITION,
    CONFIG_ID_LOW_THROTTLE_OX_POSITION,
    CONFIG_ID_LOW_THROTTLE_FUEL_POSITION,
    CONFIG_ID_IGNITER_PRESSURE_THRESHOLD,
    CONFIG_ID_PILOT_FLAME_PRESSURE_THRESHOLD,

    // Default valve parameters
    CONFIG_ID_DEFAULT_OPENING_TIME,
    CONFIG_ID_DEFAULT_MAX_APERTURE,

    // Valve speficic paramteres
    CONFIG_ID_PRZ_FIL_OPENING_TIME,
    CONFIG_ID_PRZ_FIL_MAX_APERTURE,
    CONFIG_ID_PRZ_REL_OPENING_TIME,
    CONFIG_ID_PRZ_REL_MAX_APERTURE,
    CONFIG_ID_OX_FIL_OPENING_TIME,
    CONFIG_ID_OX_FIL_MAX_APERTURE,
    CONFIG_ID_OX_REL_OPENING_TIME,
    CONFIG_ID_OX_REL_MAX_APERTURE,

    CONFIG_ID_PRZ_OX_OPENING_TIME,
    CONFIG_ID_PRZ_OX_MAX_APERTURE,
    CONFIG_ID_PRZ_FUEL_OPENING_TIME,
    CONFIG_ID_PRZ_FUEL_MAX_APERTURE,
    CONFIG_ID_OX_VEN_OPENING_TIME,
    CONFIG_ID_OX_VEN_MAX_APERTURE,
    CONFIG_ID_FUEL_VEN_OPENING_TIME,
    CONFIG_ID_FUEL_VEN_MAX_APERTURE,
    CONFIG_ID_IGN_OX_OPENING_TIME,
    CONFIG_ID_IGN_OX_MAX_APERTURE,
    CONFIG_ID_IGN_FUEL_OPENING_TIME,
    CONFIG_ID_IGN_FUEL_MAX_APERTURE,
    CONFIG_ID_MAIN_OX_OPENING_TIME,
    CONFIG_ID_MAIN_OX_MAX_APERTURE,
    CONFIG_ID_MAIN_FUEL_OPENING_TIME,
    CONFIG_ID_MAIN_FUEL_MAX_APERTURE,

    CONFIG_ID_PRZ_DET_OPENING_TIME,
    CONFIG_ID_PRZ_DET_MAX_APERTURE,
    CONFIG_ID_OX_DET_OPENING_TIME,
    CONFIG_ID_OX_DET_MAX_APERTURE,
    CONFIG_ID_PURGE_OPENING_TIME,
    CONFIG_ID_PURGE_MAX_APERTURE,

    // TARS3 parameters
    CONFIG_ID_TARS3_MASS_TARGET,
    CONFIG_ID_TARS3_PRESSURE_TARGET,
};

const char* configurationIdToName(Boardcore::ConfigurationId id);

class Registry : public Boardcore::Injectable,
                 public Boardcore::RegistryFrontend
{
public:
    Registry();

    [[nodiscard]] bool start();
};

}  // namespace RIGv3
