
all:
	g++ -std=c++11 -O2 -o logdecoder logdecoder.cpp \
				../../../skyward-boardcore/libs/tscpp/stream.cpp \
	 			-I../../../skyward-boardcore/libs -I../../boards \
	 			-I../../../skyward-boardcore/src/shared -I../../ \
				-I../../../		

clean:
	rm logdecoder
